# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import build_pb2 as build__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class BuildServiceStub(object):
    """For Performing build, and generation of the build files for the projects and
    components.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateBuildFiles = channel.unary_unary(
                '/com.xilinx.rigel.build.v1.BuildService/GenerateBuildFiles',
                request_serializer=build__pb2.BuildRequest.SerializeToString,
                response_deserializer=build__pb2.GenerateBuildFilesResponse.FromString,
                )
        self.Build = channel.unary_stream(
                '/com.xilinx.rigel.build.v1.BuildService/Build',
                request_serializer=build__pb2.BuildRequest.SerializeToString,
                response_deserializer=build__pb2.BuildResponse.FromString,
                )
        self.BuildContainer = channel.unary_stream(
                '/com.xilinx.rigel.build.v1.BuildService/BuildContainer',
                request_serializer=build__pb2.BuildRequest.SerializeToString,
                response_deserializer=build__pb2.BuildResponse.FromString,
                )
        self.PerformCustomBuild = channel.unary_stream(
                '/com.xilinx.rigel.build.v1.BuildService/PerformCustomBuild',
                request_serializer=build__pb2.BuildRequest.SerializeToString,
                response_deserializer=build__pb2.BuildResponse.FromString,
                )
        self.ListRunningBuilds = channel.unary_unary(
                '/com.xilinx.rigel.build.v1.BuildService/ListRunningBuilds',
                request_serializer=build__pb2.ListRunningBuildsRequest.SerializeToString,
                response_deserializer=build__pb2.RunningBuilds.FromString,
                )
        self.CancelRunningBuild = channel.unary_unary(
                '/com.xilinx.rigel.build.v1.BuildService/CancelRunningBuild',
                request_serializer=build__pb2.RunningBuild.SerializeToString,
                response_deserializer=build__pb2.CancelRunningBuildResponse.FromString,
                )
        self.GenerateCompileDataForCustomBuild = channel.unary_unary(
                '/com.xilinx.rigel.build.v1.BuildService/GenerateCompileDataForCustomBuild',
                request_serializer=build__pb2.BuildRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetBuildStatus = channel.unary_unary(
                '/com.xilinx.rigel.build.v1.BuildService/GetBuildStatus',
                request_serializer=build__pb2.BuildStatusRequest.SerializeToString,
                response_deserializer=build__pb2.BuildStatus.FromString,
                )
        self.updateInitiatedBuilds = channel.unary_unary(
                '/com.xilinx.rigel.build.v1.BuildService/updateInitiatedBuilds',
                request_serializer=build__pb2.UpdateInitiatedBuildsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.ReadCMakeBuildSettings = channel.unary_unary(
                '/com.xilinx.rigel.build.v1.BuildService/ReadCMakeBuildSettings',
                request_serializer=build__pb2.BuildSettingsRequest.SerializeToString,
                response_deserializer=build__pb2.ReadBuildSettingsResponse.FromString,
                )
        self.WriteCMakeBuildSettings = channel.unary_unary(
                '/com.xilinx.rigel.build.v1.BuildService/WriteCMakeBuildSettings',
                request_serializer=build__pb2.BuildSettingsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class BuildServiceServicer(object):
    """For Performing build, and generation of the build files for the projects and
    components.
    """

    def GenerateBuildFiles(self, request, context):
        """Generate CMakeFiles for the given application and an optional component
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Build(self, request, context):
        """To perform build
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuildContainer(self, request, context):
        """To perform container build
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PerformCustomBuild(self, request, context):
        """To perform Custom Build
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRunningBuilds(self, request, context):
        """List running builds
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRunningBuild(self, request, context):
        """Cancel Build
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateCompileDataForCustomBuild(self, request, context):
        """Generates compile database of custom build project
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBuildStatus(self, request, context):
        """Generates the build order for Application project
        rpc GetBuildOrder(BuildOrderRequest) returns(BuildOrder);

        Generates the build status with order
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateInitiatedBuilds(self, request, context):
        """List running builds
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadCMakeBuildSettings(self, request, context):
        """Read cmake build settings from a component or UserConfig.cmake file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteCMakeBuildSettings(self, request, context):
        """Write cmake build settings to a component or UserConfig.cmake file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BuildServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateBuildFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateBuildFiles,
                    request_deserializer=build__pb2.BuildRequest.FromString,
                    response_serializer=build__pb2.GenerateBuildFilesResponse.SerializeToString,
            ),
            'Build': grpc.unary_stream_rpc_method_handler(
                    servicer.Build,
                    request_deserializer=build__pb2.BuildRequest.FromString,
                    response_serializer=build__pb2.BuildResponse.SerializeToString,
            ),
            'BuildContainer': grpc.unary_stream_rpc_method_handler(
                    servicer.BuildContainer,
                    request_deserializer=build__pb2.BuildRequest.FromString,
                    response_serializer=build__pb2.BuildResponse.SerializeToString,
            ),
            'PerformCustomBuild': grpc.unary_stream_rpc_method_handler(
                    servicer.PerformCustomBuild,
                    request_deserializer=build__pb2.BuildRequest.FromString,
                    response_serializer=build__pb2.BuildResponse.SerializeToString,
            ),
            'ListRunningBuilds': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRunningBuilds,
                    request_deserializer=build__pb2.ListRunningBuildsRequest.FromString,
                    response_serializer=build__pb2.RunningBuilds.SerializeToString,
            ),
            'CancelRunningBuild': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRunningBuild,
                    request_deserializer=build__pb2.RunningBuild.FromString,
                    response_serializer=build__pb2.CancelRunningBuildResponse.SerializeToString,
            ),
            'GenerateCompileDataForCustomBuild': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateCompileDataForCustomBuild,
                    request_deserializer=build__pb2.BuildRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetBuildStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuildStatus,
                    request_deserializer=build__pb2.BuildStatusRequest.FromString,
                    response_serializer=build__pb2.BuildStatus.SerializeToString,
            ),
            'updateInitiatedBuilds': grpc.unary_unary_rpc_method_handler(
                    servicer.updateInitiatedBuilds,
                    request_deserializer=build__pb2.UpdateInitiatedBuildsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ReadCMakeBuildSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadCMakeBuildSettings,
                    request_deserializer=build__pb2.BuildSettingsRequest.FromString,
                    response_serializer=build__pb2.ReadBuildSettingsResponse.SerializeToString,
            ),
            'WriteCMakeBuildSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteCMakeBuildSettings,
                    request_deserializer=build__pb2.BuildSettingsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.xilinx.rigel.build.v1.BuildService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BuildService(object):
    """For Performing build, and generation of the build files for the projects and
    components.
    """

    @staticmethod
    def GenerateBuildFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.xilinx.rigel.build.v1.BuildService/GenerateBuildFiles',
            build__pb2.BuildRequest.SerializeToString,
            build__pb2.GenerateBuildFilesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Build(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/com.xilinx.rigel.build.v1.BuildService/Build',
            build__pb2.BuildRequest.SerializeToString,
            build__pb2.BuildResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BuildContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/com.xilinx.rigel.build.v1.BuildService/BuildContainer',
            build__pb2.BuildRequest.SerializeToString,
            build__pb2.BuildResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PerformCustomBuild(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/com.xilinx.rigel.build.v1.BuildService/PerformCustomBuild',
            build__pb2.BuildRequest.SerializeToString,
            build__pb2.BuildResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListRunningBuilds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.xilinx.rigel.build.v1.BuildService/ListRunningBuilds',
            build__pb2.ListRunningBuildsRequest.SerializeToString,
            build__pb2.RunningBuilds.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CancelRunningBuild(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.xilinx.rigel.build.v1.BuildService/CancelRunningBuild',
            build__pb2.RunningBuild.SerializeToString,
            build__pb2.CancelRunningBuildResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateCompileDataForCustomBuild(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.xilinx.rigel.build.v1.BuildService/GenerateCompileDataForCustomBuild',
            build__pb2.BuildRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBuildStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.xilinx.rigel.build.v1.BuildService/GetBuildStatus',
            build__pb2.BuildStatusRequest.SerializeToString,
            build__pb2.BuildStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def updateInitiatedBuilds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.xilinx.rigel.build.v1.BuildService/updateInitiatedBuilds',
            build__pb2.UpdateInitiatedBuildsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadCMakeBuildSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.xilinx.rigel.build.v1.BuildService/ReadCMakeBuildSettings',
            build__pb2.BuildSettingsRequest.SerializeToString,
            build__pb2.ReadBuildSettingsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteCMakeBuildSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.xilinx.rigel.build.v1.BuildService/WriteCMakeBuildSettings',
            build__pb2.BuildSettingsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
