# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flownavigator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='flownavigator.proto',
  package='com.xilinx.rigel.flownavigator.v2',
  syntax='proto3',
  serialized_options=b'P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x66lownavigator.proto\x12!com.xilinx.rigel.flownavigator.v2\"p\n\x18\x41pplicationStatusRequest\x12\x10\n\x08\x61pp_name\x18\x01 \x01(\t\x12\x11\n\tbuild_cfg\x18\x02 \x01(\t\x12\x17\n\x0f\x61pp_parent_path\x18\x03 \x01(\t\x12\x16\n\x0e\x63ontainer_name\x18\x04 \x01(\t\"Z\n\x19\x41pplicationStatusResponse\x12=\n\x08\x61rtifact\x18\x01 \x03(\x0b\x32+.com.xilinx.rigel.flownavigator.v2.Artifact\"\xde\x01\n\x08\x41rtifact\x12=\n\x04type\x18\x01 \x01(\x0e\x32/.com.xilinx.rigel.flownavigator.v2.ArtifactType\x12\x41\n\x06status\x18\x02 \x01(\x0e\x32\x31.com.xilinx.rigel.flownavigator.v2.ArtifactStatus\x12?\n\x05state\x18\x03 \x01(\x0e\x32\x30.com.xilinx.rigel.flownavigator.v2.ArtifactState\x12\x0f\n\x07message\x18\x04 \x01(\t\"X\n\x16\x43omponentStatusRequest\x12\x11\n\tbuild_cfg\x18\x02 \x01(\t\x12\x11\n\tcomp_name\x18\x04 \x01(\t\x12\x18\n\x10\x63omp_parent_path\x18\x05 \x01(\t\"X\n\x17\x43omponentStatusResponse\x12=\n\x08\x61rtifact\x18\x01 \x03(\x0b\x32+.com.xilinx.rigel.flownavigator.v2.Artifact*`\n\x0e\x41rtifactStatus\x12\x07\n\x03NEW\x10\x00\x12\x0f\n\x0bIN_PROGRESS\x10\x01\x12\x0b\n\x07SUCCESS\x10\x02\x12\t\n\x05\x45RROR\x10\x03\x12\x0f\n\x0bOUT_OF_DATE\x10\x04\x12\x0b\n\x07PARTIAL\x10\x05**\n\rArtifactState\x12\x0c\n\x08\x44ISABLED\x10\x00\x12\x0b\n\x07\x45NABLED\x10\x01*W\n\x0c\x41rtifactType\x12\t\n\x05\x42UILD\x10\x00\x12\x07\n\x03RUN\x10\x01\x12\t\n\x05\x44\x45\x42UG\x10\x02\x12\r\n\tEMULATION\x10\x03\x12\n\n\x06REPORT\x10\x04\x12\r\n\tBOOTIMAGE\x10\x05\x32\xbc\x02\n\x14\x46lowNavigatorService\x12\x93\x01\n\x14getApplicationStatus\x12;.com.xilinx.rigel.flownavigator.v2.ApplicationStatusRequest\x1a<.com.xilinx.rigel.flownavigator.v2.ApplicationStatusResponse\"\x00\x12\x8d\x01\n\x12getComponentStatus\x12\x39.com.xilinx.rigel.flownavigator.v2.ComponentStatusRequest\x1a:.com.xilinx.rigel.flownavigator.v2.ComponentStatusResponse\"\x00\x42\x02P\x01\x62\x06proto3'
)

_ARTIFACTSTATUS = _descriptor.EnumDescriptor(
  name='ArtifactStatus',
  full_name='com.xilinx.rigel.flownavigator.v2.ArtifactStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NEW', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='IN_PROGRESS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OUT_OF_DATE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PARTIAL', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=669,
  serialized_end=765,
)
_sym_db.RegisterEnumDescriptor(_ARTIFACTSTATUS)

ArtifactStatus = enum_type_wrapper.EnumTypeWrapper(_ARTIFACTSTATUS)
_ARTIFACTSTATE = _descriptor.EnumDescriptor(
  name='ArtifactState',
  full_name='com.xilinx.rigel.flownavigator.v2.ArtifactState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DISABLED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ENABLED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=767,
  serialized_end=809,
)
_sym_db.RegisterEnumDescriptor(_ARTIFACTSTATE)

ArtifactState = enum_type_wrapper.EnumTypeWrapper(_ARTIFACTSTATE)
_ARTIFACTTYPE = _descriptor.EnumDescriptor(
  name='ArtifactType',
  full_name='com.xilinx.rigel.flownavigator.v2.ArtifactType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BUILD', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RUN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEBUG', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EMULATION', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REPORT', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BOOTIMAGE', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=811,
  serialized_end=898,
)
_sym_db.RegisterEnumDescriptor(_ARTIFACTTYPE)

ArtifactType = enum_type_wrapper.EnumTypeWrapper(_ARTIFACTTYPE)
NEW = 0
IN_PROGRESS = 1
SUCCESS = 2
ERROR = 3
OUT_OF_DATE = 4
PARTIAL = 5
DISABLED = 0
ENABLED = 1
BUILD = 0
RUN = 1
DEBUG = 2
EMULATION = 3
REPORT = 4
BOOTIMAGE = 5



_APPLICATIONSTATUSREQUEST = _descriptor.Descriptor(
  name='ApplicationStatusRequest',
  full_name='com.xilinx.rigel.flownavigator.v2.ApplicationStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='app_name', full_name='com.xilinx.rigel.flownavigator.v2.ApplicationStatusRequest.app_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='build_cfg', full_name='com.xilinx.rigel.flownavigator.v2.ApplicationStatusRequest.build_cfg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='app_parent_path', full_name='com.xilinx.rigel.flownavigator.v2.ApplicationStatusRequest.app_parent_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='container_name', full_name='com.xilinx.rigel.flownavigator.v2.ApplicationStatusRequest.container_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=170,
)


_APPLICATIONSTATUSRESPONSE = _descriptor.Descriptor(
  name='ApplicationStatusResponse',
  full_name='com.xilinx.rigel.flownavigator.v2.ApplicationStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='artifact', full_name='com.xilinx.rigel.flownavigator.v2.ApplicationStatusResponse.artifact', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=262,
)


_ARTIFACT = _descriptor.Descriptor(
  name='Artifact',
  full_name='com.xilinx.rigel.flownavigator.v2.Artifact',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='com.xilinx.rigel.flownavigator.v2.Artifact.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='com.xilinx.rigel.flownavigator.v2.Artifact.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='com.xilinx.rigel.flownavigator.v2.Artifact.state', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='com.xilinx.rigel.flownavigator.v2.Artifact.message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=487,
)


_COMPONENTSTATUSREQUEST = _descriptor.Descriptor(
  name='ComponentStatusRequest',
  full_name='com.xilinx.rigel.flownavigator.v2.ComponentStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='build_cfg', full_name='com.xilinx.rigel.flownavigator.v2.ComponentStatusRequest.build_cfg', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='comp_name', full_name='com.xilinx.rigel.flownavigator.v2.ComponentStatusRequest.comp_name', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='comp_parent_path', full_name='com.xilinx.rigel.flownavigator.v2.ComponentStatusRequest.comp_parent_path', index=2,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=489,
  serialized_end=577,
)


_COMPONENTSTATUSRESPONSE = _descriptor.Descriptor(
  name='ComponentStatusResponse',
  full_name='com.xilinx.rigel.flownavigator.v2.ComponentStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='artifact', full_name='com.xilinx.rigel.flownavigator.v2.ComponentStatusResponse.artifact', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=579,
  serialized_end=667,
)

_APPLICATIONSTATUSRESPONSE.fields_by_name['artifact'].message_type = _ARTIFACT
_ARTIFACT.fields_by_name['type'].enum_type = _ARTIFACTTYPE
_ARTIFACT.fields_by_name['status'].enum_type = _ARTIFACTSTATUS
_ARTIFACT.fields_by_name['state'].enum_type = _ARTIFACTSTATE
_COMPONENTSTATUSRESPONSE.fields_by_name['artifact'].message_type = _ARTIFACT
DESCRIPTOR.message_types_by_name['ApplicationStatusRequest'] = _APPLICATIONSTATUSREQUEST
DESCRIPTOR.message_types_by_name['ApplicationStatusResponse'] = _APPLICATIONSTATUSRESPONSE
DESCRIPTOR.message_types_by_name['Artifact'] = _ARTIFACT
DESCRIPTOR.message_types_by_name['ComponentStatusRequest'] = _COMPONENTSTATUSREQUEST
DESCRIPTOR.message_types_by_name['ComponentStatusResponse'] = _COMPONENTSTATUSRESPONSE
DESCRIPTOR.enum_types_by_name['ArtifactStatus'] = _ARTIFACTSTATUS
DESCRIPTOR.enum_types_by_name['ArtifactState'] = _ARTIFACTSTATE
DESCRIPTOR.enum_types_by_name['ArtifactType'] = _ARTIFACTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ApplicationStatusRequest = _reflection.GeneratedProtocolMessageType('ApplicationStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _APPLICATIONSTATUSREQUEST,
  '__module__' : 'flownavigator_pb2'
  # @@protoc_insertion_point(class_scope:com.xilinx.rigel.flownavigator.v2.ApplicationStatusRequest)
  })
_sym_db.RegisterMessage(ApplicationStatusRequest)

ApplicationStatusResponse = _reflection.GeneratedProtocolMessageType('ApplicationStatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _APPLICATIONSTATUSRESPONSE,
  '__module__' : 'flownavigator_pb2'
  # @@protoc_insertion_point(class_scope:com.xilinx.rigel.flownavigator.v2.ApplicationStatusResponse)
  })
_sym_db.RegisterMessage(ApplicationStatusResponse)

Artifact = _reflection.GeneratedProtocolMessageType('Artifact', (_message.Message,), {
  'DESCRIPTOR' : _ARTIFACT,
  '__module__' : 'flownavigator_pb2'
  # @@protoc_insertion_point(class_scope:com.xilinx.rigel.flownavigator.v2.Artifact)
  })
_sym_db.RegisterMessage(Artifact)

ComponentStatusRequest = _reflection.GeneratedProtocolMessageType('ComponentStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMPONENTSTATUSREQUEST,
  '__module__' : 'flownavigator_pb2'
  # @@protoc_insertion_point(class_scope:com.xilinx.rigel.flownavigator.v2.ComponentStatusRequest)
  })
_sym_db.RegisterMessage(ComponentStatusRequest)

ComponentStatusResponse = _reflection.GeneratedProtocolMessageType('ComponentStatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _COMPONENTSTATUSRESPONSE,
  '__module__' : 'flownavigator_pb2'
  # @@protoc_insertion_point(class_scope:com.xilinx.rigel.flownavigator.v2.ComponentStatusResponse)
  })
_sym_db.RegisterMessage(ComponentStatusResponse)


DESCRIPTOR._options = None

_FLOWNAVIGATORSERVICE = _descriptor.ServiceDescriptor(
  name='FlowNavigatorService',
  full_name='com.xilinx.rigel.flownavigator.v2.FlowNavigatorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=901,
  serialized_end=1217,
  methods=[
  _descriptor.MethodDescriptor(
    name='getApplicationStatus',
    full_name='com.xilinx.rigel.flownavigator.v2.FlowNavigatorService.getApplicationStatus',
    index=0,
    containing_service=None,
    input_type=_APPLICATIONSTATUSREQUEST,
    output_type=_APPLICATIONSTATUSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getComponentStatus',
    full_name='com.xilinx.rigel.flownavigator.v2.FlowNavigatorService.getComponentStatus',
    index=1,
    containing_service=None,
    input_type=_COMPONENTSTATUSREQUEST,
    output_type=_COMPONENTSTATUSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FLOWNAVIGATORSERVICE)

DESCRIPTOR.services_by_name['FlowNavigatorService'] = _FLOWNAVIGATORSERVICE

# @@protoc_insertion_point(module_scope)
