# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import hls_report_pb2 as hls__report__pb2


class HLSReportStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getHLSReportData = channel.unary_unary(
                '/xilinx.rigel.hls.report.HLSReport/getHLSReportData',
                request_serializer=hls__report__pb2.ReportRequest.SerializeToString,
                response_deserializer=hls__report__pb2.ReportReply.FromString,
                )
        self.getCosimReportData = channel.unary_unary(
                '/xilinx.rigel.hls.report.HLSReport/getCosimReportData',
                request_serializer=hls__report__pb2.ReportRequest.SerializeToString,
                response_deserializer=hls__report__pb2.CosimReportResponse.FromString,
                )


class HLSReportServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getHLSReportData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCosimReportData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HLSReportServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getHLSReportData': grpc.unary_unary_rpc_method_handler(
                    servicer.getHLSReportData,
                    request_deserializer=hls__report__pb2.ReportRequest.FromString,
                    response_serializer=hls__report__pb2.ReportReply.SerializeToString,
            ),
            'getCosimReportData': grpc.unary_unary_rpc_method_handler(
                    servicer.getCosimReportData,
                    request_deserializer=hls__report__pb2.ReportRequest.FromString,
                    response_serializer=hls__report__pb2.CosimReportResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xilinx.rigel.hls.report.HLSReport', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HLSReport(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getHLSReportData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.hls.report.HLSReport/getHLSReportData',
            hls__report__pb2.ReportRequest.SerializeToString,
            hls__report__pb2.ReportReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getCosimReportData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.hls.report.HLSReport/getCosimReportData',
            hls__report__pb2.ReportRequest.SerializeToString,
            hls__report__pb2.CosimReportResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
