# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import hls_scheduleviewer_pb2 as hls__scheduleviewer__pb2


class ModuleManagerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRootGanttNode = channel.unary_unary(
                '/xilinx.rigel.hls.adb.ModuleManagerService/GetRootGanttNode',
                request_serializer=hls__scheduleviewer__pb2.GetRootGanttNodeRequest.SerializeToString,
                response_deserializer=hls__scheduleviewer__pb2.RootGanttNodeResponse.FromString,
                )
        self.GetGanttNodeProperties = channel.unary_unary(
                '/xilinx.rigel.hls.adb.ModuleManagerService/GetGanttNodeProperties',
                request_serializer=hls__scheduleviewer__pb2.GetGanttNodePropertiesRequest.SerializeToString,
                response_deserializer=hls__scheduleviewer__pb2.GanttNodePropertiesResponse.FromString,
                )


class ModuleManagerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRootGanttNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGanttNodeProperties(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModuleManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRootGanttNode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRootGanttNode,
                    request_deserializer=hls__scheduleviewer__pb2.GetRootGanttNodeRequest.FromString,
                    response_serializer=hls__scheduleviewer__pb2.RootGanttNodeResponse.SerializeToString,
            ),
            'GetGanttNodeProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGanttNodeProperties,
                    request_deserializer=hls__scheduleviewer__pb2.GetGanttNodePropertiesRequest.FromString,
                    response_serializer=hls__scheduleviewer__pb2.GanttNodePropertiesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xilinx.rigel.hls.adb.ModuleManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ModuleManagerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRootGanttNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.hls.adb.ModuleManagerService/GetRootGanttNode',
            hls__scheduleviewer__pb2.GetRootGanttNodeRequest.SerializeToString,
            hls__scheduleviewer__pb2.RootGanttNodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGanttNodeProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.hls.adb.ModuleManagerService/GetGanttNodeProperties',
            hls__scheduleviewer__pb2.GetGanttNodePropertiesRequest.SerializeToString,
            hls__scheduleviewer__pb2.GanttNodePropertiesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
