# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hls_timeline.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hls_timeline.proto',
  package='xilinx.rigel.hls.timeline',
  syntax='proto3',
  serialized_options=b'\n\'com.xilinx.hls.server.proto.hlsTimelineB\020HlsTimelineProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12hls_timeline.proto\x12\x19xilinx.rigel.hls.timeline\"6\n\x0fTimelineRequest\x12#\n\x1btimeline_solution_directory\x18\x01 \x01(\t\"K\n\x10TimelineResponse\x12\x37\n\x05\x65ntry\x18\x01 \x03(\x0b\x32(.xilinx.rigel.hls.timeline.TimelineEntry\"\xc8\x01\n\rTimelineEntry\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05label\x18\x02 \x01(\t\x12\x11\n\tparent_id\x18\x03 \x01(\x05\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x37\n\x05range\x18\x05 \x01(\x0b\x32(.xilinx.rigel.hls.timeline.TimelineRange\x12\x42\n\x06status\x18\x06 \x03(\x0b\x32\x32.xilinx.rigel.hls.timeline.TimelineRowElementModel\"+\n\rTimelineRange\x12\r\n\x05start\x18\x01 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x05\"m\n\x17TimelineRowElementModel\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x37\n\x05range\x18\x02 \x01(\x0b\x32(.xilinx.rigel.hls.timeline.TimelineRange\x12\r\n\x05label\x18\x03 \x01(\t2{\n\x0bHLSTimeline\x12l\n\x0fgetTimelineData\x12*.xilinx.rigel.hls.timeline.TimelineRequest\x1a+.xilinx.rigel.hls.timeline.TimelineResponse\"\x00\x42=\n\'com.xilinx.hls.server.proto.hlsTimelineB\x10HlsTimelineProtoP\x01\x62\x06proto3'
)




_TIMELINEREQUEST = _descriptor.Descriptor(
  name='TimelineRequest',
  full_name='xilinx.rigel.hls.timeline.TimelineRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeline_solution_directory', full_name='xilinx.rigel.hls.timeline.TimelineRequest.timeline_solution_directory', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=103,
)


_TIMELINERESPONSE = _descriptor.Descriptor(
  name='TimelineResponse',
  full_name='xilinx.rigel.hls.timeline.TimelineResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entry', full_name='xilinx.rigel.hls.timeline.TimelineResponse.entry', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=180,
)


_TIMELINEENTRY = _descriptor.Descriptor(
  name='TimelineEntry',
  full_name='xilinx.rigel.hls.timeline.TimelineEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='xilinx.rigel.hls.timeline.TimelineEntry.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='label', full_name='xilinx.rigel.hls.timeline.TimelineEntry.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parent_id', full_name='xilinx.rigel.hls.timeline.TimelineEntry.parent_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='xilinx.rigel.hls.timeline.TimelineEntry.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='range', full_name='xilinx.rigel.hls.timeline.TimelineEntry.range', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='xilinx.rigel.hls.timeline.TimelineEntry.status', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=383,
)


_TIMELINERANGE = _descriptor.Descriptor(
  name='TimelineRange',
  full_name='xilinx.rigel.hls.timeline.TimelineRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='xilinx.rigel.hls.timeline.TimelineRange.start', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end', full_name='xilinx.rigel.hls.timeline.TimelineRange.end', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=428,
)


_TIMELINEROWELEMENTMODEL = _descriptor.Descriptor(
  name='TimelineRowElementModel',
  full_name='xilinx.rigel.hls.timeline.TimelineRowElementModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='xilinx.rigel.hls.timeline.TimelineRowElementModel.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='range', full_name='xilinx.rigel.hls.timeline.TimelineRowElementModel.range', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='label', full_name='xilinx.rigel.hls.timeline.TimelineRowElementModel.label', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=430,
  serialized_end=539,
)

_TIMELINERESPONSE.fields_by_name['entry'].message_type = _TIMELINEENTRY
_TIMELINEENTRY.fields_by_name['range'].message_type = _TIMELINERANGE
_TIMELINEENTRY.fields_by_name['status'].message_type = _TIMELINEROWELEMENTMODEL
_TIMELINEROWELEMENTMODEL.fields_by_name['range'].message_type = _TIMELINERANGE
DESCRIPTOR.message_types_by_name['TimelineRequest'] = _TIMELINEREQUEST
DESCRIPTOR.message_types_by_name['TimelineResponse'] = _TIMELINERESPONSE
DESCRIPTOR.message_types_by_name['TimelineEntry'] = _TIMELINEENTRY
DESCRIPTOR.message_types_by_name['TimelineRange'] = _TIMELINERANGE
DESCRIPTOR.message_types_by_name['TimelineRowElementModel'] = _TIMELINEROWELEMENTMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimelineRequest = _reflection.GeneratedProtocolMessageType('TimelineRequest', (_message.Message,), {
  'DESCRIPTOR' : _TIMELINEREQUEST,
  '__module__' : 'hls_timeline_pb2'
  # @@protoc_insertion_point(class_scope:xilinx.rigel.hls.timeline.TimelineRequest)
  })
_sym_db.RegisterMessage(TimelineRequest)

TimelineResponse = _reflection.GeneratedProtocolMessageType('TimelineResponse', (_message.Message,), {
  'DESCRIPTOR' : _TIMELINERESPONSE,
  '__module__' : 'hls_timeline_pb2'
  # @@protoc_insertion_point(class_scope:xilinx.rigel.hls.timeline.TimelineResponse)
  })
_sym_db.RegisterMessage(TimelineResponse)

TimelineEntry = _reflection.GeneratedProtocolMessageType('TimelineEntry', (_message.Message,), {
  'DESCRIPTOR' : _TIMELINEENTRY,
  '__module__' : 'hls_timeline_pb2'
  # @@protoc_insertion_point(class_scope:xilinx.rigel.hls.timeline.TimelineEntry)
  })
_sym_db.RegisterMessage(TimelineEntry)

TimelineRange = _reflection.GeneratedProtocolMessageType('TimelineRange', (_message.Message,), {
  'DESCRIPTOR' : _TIMELINERANGE,
  '__module__' : 'hls_timeline_pb2'
  # @@protoc_insertion_point(class_scope:xilinx.rigel.hls.timeline.TimelineRange)
  })
_sym_db.RegisterMessage(TimelineRange)

TimelineRowElementModel = _reflection.GeneratedProtocolMessageType('TimelineRowElementModel', (_message.Message,), {
  'DESCRIPTOR' : _TIMELINEROWELEMENTMODEL,
  '__module__' : 'hls_timeline_pb2'
  # @@protoc_insertion_point(class_scope:xilinx.rigel.hls.timeline.TimelineRowElementModel)
  })
_sym_db.RegisterMessage(TimelineRowElementModel)


DESCRIPTOR._options = None

_HLSTIMELINE = _descriptor.ServiceDescriptor(
  name='HLSTimeline',
  full_name='xilinx.rigel.hls.timeline.HLSTimeline',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=541,
  serialized_end=664,
  methods=[
  _descriptor.MethodDescriptor(
    name='getTimelineData',
    full_name='xilinx.rigel.hls.timeline.HLSTimeline.getTimelineData',
    index=0,
    containing_service=None,
    input_type=_TIMELINEREQUEST,
    output_type=_TIMELINERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HLSTIMELINE)

DESCRIPTOR.services_by_name['HLSTimeline'] = _HLSTIMELINE

# @@protoc_insertion_point(module_scope)
