# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import bsp_pb2 as bsp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import platform_pb2 as platform__pb2


class PlatformStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePlatform = channel.unary_stream(
                '/xilinx.rigel.platform.v3.Platform/CreatePlatform',
                request_serializer=platform__pb2.CreatePlatformRequest.SerializeToString,
                response_deserializer=platform__pb2.PlatformResponse.FromString,
                )
        self.GetPlatform = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/GetPlatform',
                request_serializer=platform__pb2.GetPlatformRequest.SerializeToString,
                response_deserializer=platform__pb2.PlatformComponent.FromString,
                )
        self.ListPlatformComponents = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/ListPlatformComponents',
                request_serializer=platform__pb2.ListPlatformComponentsRequest.SerializeToString,
                response_deserializer=platform__pb2.ListPlatformComponentsResponse.FromString,
                )
        self.UpdatePlatformComponent = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/UpdatePlatformComponent',
                request_serializer=platform__pb2.UpdatePlatformComponentRequest.SerializeToString,
                response_deserializer=platform__pb2.PlatformComponent.FromString,
                )
        self.ListDomains = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/ListDomains',
                request_serializer=platform__pb2.ListDomainRequest.SerializeToString,
                response_deserializer=platform__pb2.ListDomainsResponse.FromString,
                )
        self.AddDomain = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/AddDomain',
                request_serializer=platform__pb2.AddDomainRequest.SerializeToString,
                response_deserializer=platform__pb2.Domain.FromString,
                )
        self.DeleteDomain = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/DeleteDomain',
                request_serializer=platform__pb2.DeleteDomainRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.UpdateDomain = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/UpdateDomain',
                request_serializer=platform__pb2.UpdateDomainRequest.SerializeToString,
                response_deserializer=platform__pb2.Domain.FromString,
                )
        self.GeneratePlatform = channel.unary_stream(
                '/xilinx.rigel.platform.v3.Platform/GeneratePlatform',
                request_serializer=platform__pb2.GeneratePlatformRequest.SerializeToString,
                response_deserializer=platform__pb2.PlatformResponse.FromString,
                )
        self.GetDomain = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/GetDomain',
                request_serializer=platform__pb2.GetDomainRequest.SerializeToString,
                response_deserializer=platform__pb2.Domain.FromString,
                )
        self.GetProcessorOSList = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/GetProcessorOSList',
                request_serializer=platform__pb2.GetProcessorOSListRequest.SerializeToString,
                response_deserializer=platform__pb2.OSProcessorList.FromString,
                )
        self.GetTemplateList = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/GetTemplateList',
                request_serializer=platform__pb2.GetTemplateRequest.SerializeToString,
                response_deserializer=platform__pb2.TemplateList.FromString,
                )
        self.RetargetFSBL = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/RetargetFSBL',
                request_serializer=platform__pb2.ReTargetFSBLRequest.SerializeToString,
                response_deserializer=platform__pb2.Domain.FromString,
                )
        self.GetBSPData = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/GetBSPData',
                request_serializer=bsp__pb2.BSPDataRequest.SerializeToString,
                response_deserializer=bsp__pb2.BSPData.FromString,
                )
        self.GetDrivers = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/GetDrivers',
                request_serializer=bsp__pb2.BSPDataRequest.SerializeToString,
                response_deserializer=bsp__pb2.BSPDriversResponse.FromString,
                )
        self.GetConfiguredLibraries = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/GetConfiguredLibraries',
                request_serializer=bsp__pb2.BSPDataRequest.SerializeToString,
                response_deserializer=bsp__pb2.BSPLibrariesResponse.FromString,
                )
        self.GetSupportedLibraries = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/GetSupportedLibraries',
                request_serializer=bsp__pb2.BSPDataRequest.SerializeToString,
                response_deserializer=bsp__pb2.BSPLibrariesResponse.FromString,
                )
        self.GetBSPOSInfo = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/GetBSPOSInfo',
                request_serializer=bsp__pb2.BSPDataRequest.SerializeToString,
                response_deserializer=bsp__pb2.OS.FromString,
                )
        self.GetBSPProcessorInfo = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/GetBSPProcessorInfo',
                request_serializer=bsp__pb2.BSPDataRequest.SerializeToString,
                response_deserializer=bsp__pb2.Processor.FromString,
                )
        self.ListBSPParameters = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/ListBSPParameters',
                request_serializer=bsp__pb2.BSPParameterRequest.SerializeToString,
                response_deserializer=bsp__pb2.BSPParameterResponse.FromString,
                )
        self.ListBSPLibraryParameters = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/ListBSPLibraryParameters',
                request_serializer=bsp__pb2.BSPLibraryRequest.SerializeToString,
                response_deserializer=bsp__pb2.BSPParameterResponse.FromString,
                )
        self.UpdateBSPParameter = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/UpdateBSPParameter',
                request_serializer=bsp__pb2.BSPParameterUpdateRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.UpdateBSPLibraryParameter = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/UpdateBSPLibraryParameter',
                request_serializer=bsp__pb2.BSPLibraryParameterUpdateRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.AddBSPLibrary = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/AddBSPLibrary',
                request_serializer=bsp__pb2.BSPLibraryRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.RemoveBSPLibrary = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/RemoveBSPLibrary',
                request_serializer=bsp__pb2.BSPLibraryRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetBSPParameter = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/GetBSPParameter',
                request_serializer=bsp__pb2.BSPParameterDataRequest.SerializeToString,
                response_deserializer=bsp__pb2.BSPParameter.FromString,
                )
        self.GetBSPLibraryParameter = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/GetBSPLibraryParameter',
                request_serializer=bsp__pb2.BSPLibraryParameterDataRequest.SerializeToString,
                response_deserializer=bsp__pb2.BSPParameter.FromString,
                )
        self.validateBSP = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/validateBSP',
                request_serializer=platform__pb2.ValidateTemplateRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.RegenerateBSP = channel.unary_stream(
                '/xilinx.rigel.platform.v3.Platform/RegenerateBSP',
                request_serializer=bsp__pb2.RegenerateBSPRequest.SerializeToString,
                response_deserializer=platform__pb2.PlatformResponse.FromString,
                )
        self.CleanPlatform = channel.unary_stream(
                '/xilinx.rigel.platform.v3.Platform/CleanPlatform',
                request_serializer=platform__pb2.CleanPlatformRequest.SerializeToString,
                response_deserializer=platform__pb2.PlatformResponse.FromString,
                )
        self.UpdateHwXSA = channel.unary_stream(
                '/xilinx.rigel.platform.v3.Platform/UpdateHwXSA',
                request_serializer=platform__pb2.UpdatePlatformRequest.SerializeToString,
                response_deserializer=platform__pb2.PlatformResponse.FromString,
                )
        self.GenerateBif = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/GenerateBif',
                request_serializer=platform__pb2.GenerateBifRequest.SerializeToString,
                response_deserializer=platform__pb2.Domain.FromString,
                )
        self.GenerateEmbeddedRepoData = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/GenerateEmbeddedRepoData',
                request_serializer=platform__pb2.GenerateEmbeddedRepoDataRequest.SerializeToString,
                response_deserializer=platform__pb2.GenerateEmbeddedRepoDataResponse.FromString,
                )
        self.GetEmbeddedRepoData = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/GetEmbeddedRepoData',
                request_serializer=platform__pb2.GetEmbeddedRepoDataRequest.SerializeToString,
                response_deserializer=platform__pb2.GetEmbeddedRepoDataResponse.FromString,
                )
        self.SetEmbeddedRepoData = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/SetEmbeddedRepoData',
                request_serializer=platform__pb2.SetEmbeddedRepoDataRequest.SerializeToString,
                response_deserializer=platform__pb2.SetEmbeddedRepoDataResponse.FromString,
                )
        self.UpdateBSPPropertyPath = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/UpdateBSPPropertyPath',
                request_serializer=bsp__pb2.BSPUpdatePathRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetHwXsaSpecification = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/GetHwXsaSpecification',
                request_serializer=platform__pb2.HwXsaDataRequest.SerializeToString,
                response_deserializer=platform__pb2.HwXsaDataResponse.FromString,
                )
        self.GetHWXSAPropertyInfo = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/GetHWXSAPropertyInfo',
                request_serializer=platform__pb2.HWXSAPropertyInfoRequest.SerializeToString,
                response_deserializer=platform__pb2.HWXSAPropertyInfoResponse.FromString,
                )
        self.ExtractHwFiles = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/ExtractHwFiles',
                request_serializer=platform__pb2.ExtractHwFilesRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetPartFromXSA = channel.unary_unary(
                '/xilinx.rigel.platform.v3.Platform/GetPartFromXSA',
                request_serializer=platform__pb2.GetPartFromXSARequest.SerializeToString,
                response_deserializer=platform__pb2.GetPartFromXSAResponse.FromString,
                )


class PlatformServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePlatform(self, request, context):
        """Create a new component of the specified type in the workspace
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlatform(self, request, context):
        """API to get the platform
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlatformComponents(self, request, context):
        """API to get list of platform Components
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePlatformComponent(self, request, context):
        """API to update platform component
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDomains(self, request, context):
        """
        Returns a list of all domains in the platform.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddDomain(self, request, context):
        """Create a new domain of the specified type in the platform
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDomain(self, request, context):
        """Deletes the component with the specified id from the application project
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDomain(self, request, context):
        """Create a new component of the specified type in the workspace
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GeneratePlatform(self, request, context):
        """Generates the platform
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDomain(self, request, context):
        """Create a new component of the specified type in the workspace
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcessorOSList(self, request, context):
        """Get Processor OS list
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTemplateList(self, request, context):
        """Get Template list
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetargetFSBL(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBSPData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDrivers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfiguredLibraries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSupportedLibraries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBSPOSInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBSPProcessorInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBSPParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBSPLibraryParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBSPParameter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBSPLibraryParameter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBSPLibrary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveBSPLibrary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBSPParameter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBSPLibraryParameter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def validateBSP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegenerateBSP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CleanPlatform(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateHwXSA(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateBif(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateEmbeddedRepoData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmbeddedRepoData(self, request, context):
        """Retrieve the Embedded Sw Repositories information.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetEmbeddedRepoData(self, request, context):
        """Update the Embedded Sw Repositories information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBSPPropertyPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHwXsaSpecification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHWXSAPropertyInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractHwFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPartFromXSA(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlatformServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePlatform': grpc.unary_stream_rpc_method_handler(
                    servicer.CreatePlatform,
                    request_deserializer=platform__pb2.CreatePlatformRequest.FromString,
                    response_serializer=platform__pb2.PlatformResponse.SerializeToString,
            ),
            'GetPlatform': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlatform,
                    request_deserializer=platform__pb2.GetPlatformRequest.FromString,
                    response_serializer=platform__pb2.PlatformComponent.SerializeToString,
            ),
            'ListPlatformComponents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlatformComponents,
                    request_deserializer=platform__pb2.ListPlatformComponentsRequest.FromString,
                    response_serializer=platform__pb2.ListPlatformComponentsResponse.SerializeToString,
            ),
            'UpdatePlatformComponent': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePlatformComponent,
                    request_deserializer=platform__pb2.UpdatePlatformComponentRequest.FromString,
                    response_serializer=platform__pb2.PlatformComponent.SerializeToString,
            ),
            'ListDomains': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDomains,
                    request_deserializer=platform__pb2.ListDomainRequest.FromString,
                    response_serializer=platform__pb2.ListDomainsResponse.SerializeToString,
            ),
            'AddDomain': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDomain,
                    request_deserializer=platform__pb2.AddDomainRequest.FromString,
                    response_serializer=platform__pb2.Domain.SerializeToString,
            ),
            'DeleteDomain': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDomain,
                    request_deserializer=platform__pb2.DeleteDomainRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpdateDomain': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDomain,
                    request_deserializer=platform__pb2.UpdateDomainRequest.FromString,
                    response_serializer=platform__pb2.Domain.SerializeToString,
            ),
            'GeneratePlatform': grpc.unary_stream_rpc_method_handler(
                    servicer.GeneratePlatform,
                    request_deserializer=platform__pb2.GeneratePlatformRequest.FromString,
                    response_serializer=platform__pb2.PlatformResponse.SerializeToString,
            ),
            'GetDomain': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDomain,
                    request_deserializer=platform__pb2.GetDomainRequest.FromString,
                    response_serializer=platform__pb2.Domain.SerializeToString,
            ),
            'GetProcessorOSList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcessorOSList,
                    request_deserializer=platform__pb2.GetProcessorOSListRequest.FromString,
                    response_serializer=platform__pb2.OSProcessorList.SerializeToString,
            ),
            'GetTemplateList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTemplateList,
                    request_deserializer=platform__pb2.GetTemplateRequest.FromString,
                    response_serializer=platform__pb2.TemplateList.SerializeToString,
            ),
            'RetargetFSBL': grpc.unary_unary_rpc_method_handler(
                    servicer.RetargetFSBL,
                    request_deserializer=platform__pb2.ReTargetFSBLRequest.FromString,
                    response_serializer=platform__pb2.Domain.SerializeToString,
            ),
            'GetBSPData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBSPData,
                    request_deserializer=bsp__pb2.BSPDataRequest.FromString,
                    response_serializer=bsp__pb2.BSPData.SerializeToString,
            ),
            'GetDrivers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDrivers,
                    request_deserializer=bsp__pb2.BSPDataRequest.FromString,
                    response_serializer=bsp__pb2.BSPDriversResponse.SerializeToString,
            ),
            'GetConfiguredLibraries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfiguredLibraries,
                    request_deserializer=bsp__pb2.BSPDataRequest.FromString,
                    response_serializer=bsp__pb2.BSPLibrariesResponse.SerializeToString,
            ),
            'GetSupportedLibraries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSupportedLibraries,
                    request_deserializer=bsp__pb2.BSPDataRequest.FromString,
                    response_serializer=bsp__pb2.BSPLibrariesResponse.SerializeToString,
            ),
            'GetBSPOSInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBSPOSInfo,
                    request_deserializer=bsp__pb2.BSPDataRequest.FromString,
                    response_serializer=bsp__pb2.OS.SerializeToString,
            ),
            'GetBSPProcessorInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBSPProcessorInfo,
                    request_deserializer=bsp__pb2.BSPDataRequest.FromString,
                    response_serializer=bsp__pb2.Processor.SerializeToString,
            ),
            'ListBSPParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBSPParameters,
                    request_deserializer=bsp__pb2.BSPParameterRequest.FromString,
                    response_serializer=bsp__pb2.BSPParameterResponse.SerializeToString,
            ),
            'ListBSPLibraryParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBSPLibraryParameters,
                    request_deserializer=bsp__pb2.BSPLibraryRequest.FromString,
                    response_serializer=bsp__pb2.BSPParameterResponse.SerializeToString,
            ),
            'UpdateBSPParameter': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBSPParameter,
                    request_deserializer=bsp__pb2.BSPParameterUpdateRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpdateBSPLibraryParameter': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBSPLibraryParameter,
                    request_deserializer=bsp__pb2.BSPLibraryParameterUpdateRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AddBSPLibrary': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBSPLibrary,
                    request_deserializer=bsp__pb2.BSPLibraryRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RemoveBSPLibrary': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveBSPLibrary,
                    request_deserializer=bsp__pb2.BSPLibraryRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetBSPParameter': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBSPParameter,
                    request_deserializer=bsp__pb2.BSPParameterDataRequest.FromString,
                    response_serializer=bsp__pb2.BSPParameter.SerializeToString,
            ),
            'GetBSPLibraryParameter': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBSPLibraryParameter,
                    request_deserializer=bsp__pb2.BSPLibraryParameterDataRequest.FromString,
                    response_serializer=bsp__pb2.BSPParameter.SerializeToString,
            ),
            'validateBSP': grpc.unary_unary_rpc_method_handler(
                    servicer.validateBSP,
                    request_deserializer=platform__pb2.ValidateTemplateRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RegenerateBSP': grpc.unary_stream_rpc_method_handler(
                    servicer.RegenerateBSP,
                    request_deserializer=bsp__pb2.RegenerateBSPRequest.FromString,
                    response_serializer=platform__pb2.PlatformResponse.SerializeToString,
            ),
            'CleanPlatform': grpc.unary_stream_rpc_method_handler(
                    servicer.CleanPlatform,
                    request_deserializer=platform__pb2.CleanPlatformRequest.FromString,
                    response_serializer=platform__pb2.PlatformResponse.SerializeToString,
            ),
            'UpdateHwXSA': grpc.unary_stream_rpc_method_handler(
                    servicer.UpdateHwXSA,
                    request_deserializer=platform__pb2.UpdatePlatformRequest.FromString,
                    response_serializer=platform__pb2.PlatformResponse.SerializeToString,
            ),
            'GenerateBif': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateBif,
                    request_deserializer=platform__pb2.GenerateBifRequest.FromString,
                    response_serializer=platform__pb2.Domain.SerializeToString,
            ),
            'GenerateEmbeddedRepoData': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateEmbeddedRepoData,
                    request_deserializer=platform__pb2.GenerateEmbeddedRepoDataRequest.FromString,
                    response_serializer=platform__pb2.GenerateEmbeddedRepoDataResponse.SerializeToString,
            ),
            'GetEmbeddedRepoData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmbeddedRepoData,
                    request_deserializer=platform__pb2.GetEmbeddedRepoDataRequest.FromString,
                    response_serializer=platform__pb2.GetEmbeddedRepoDataResponse.SerializeToString,
            ),
            'SetEmbeddedRepoData': grpc.unary_unary_rpc_method_handler(
                    servicer.SetEmbeddedRepoData,
                    request_deserializer=platform__pb2.SetEmbeddedRepoDataRequest.FromString,
                    response_serializer=platform__pb2.SetEmbeddedRepoDataResponse.SerializeToString,
            ),
            'UpdateBSPPropertyPath': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBSPPropertyPath,
                    request_deserializer=bsp__pb2.BSPUpdatePathRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetHwXsaSpecification': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHwXsaSpecification,
                    request_deserializer=platform__pb2.HwXsaDataRequest.FromString,
                    response_serializer=platform__pb2.HwXsaDataResponse.SerializeToString,
            ),
            'GetHWXSAPropertyInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHWXSAPropertyInfo,
                    request_deserializer=platform__pb2.HWXSAPropertyInfoRequest.FromString,
                    response_serializer=platform__pb2.HWXSAPropertyInfoResponse.SerializeToString,
            ),
            'ExtractHwFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractHwFiles,
                    request_deserializer=platform__pb2.ExtractHwFilesRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetPartFromXSA': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPartFromXSA,
                    request_deserializer=platform__pb2.GetPartFromXSARequest.FromString,
                    response_serializer=platform__pb2.GetPartFromXSAResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xilinx.rigel.platform.v3.Platform', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Platform(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePlatform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/xilinx.rigel.platform.v3.Platform/CreatePlatform',
            platform__pb2.CreatePlatformRequest.SerializeToString,
            platform__pb2.PlatformResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPlatform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/GetPlatform',
            platform__pb2.GetPlatformRequest.SerializeToString,
            platform__pb2.PlatformComponent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListPlatformComponents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/ListPlatformComponents',
            platform__pb2.ListPlatformComponentsRequest.SerializeToString,
            platform__pb2.ListPlatformComponentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePlatformComponent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/UpdatePlatformComponent',
            platform__pb2.UpdatePlatformComponentRequest.SerializeToString,
            platform__pb2.PlatformComponent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListDomains(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/ListDomains',
            platform__pb2.ListDomainRequest.SerializeToString,
            platform__pb2.ListDomainsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddDomain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/AddDomain',
            platform__pb2.AddDomainRequest.SerializeToString,
            platform__pb2.Domain.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteDomain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/DeleteDomain',
            platform__pb2.DeleteDomainRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateDomain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/UpdateDomain',
            platform__pb2.UpdateDomainRequest.SerializeToString,
            platform__pb2.Domain.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GeneratePlatform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/xilinx.rigel.platform.v3.Platform/GeneratePlatform',
            platform__pb2.GeneratePlatformRequest.SerializeToString,
            platform__pb2.PlatformResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDomain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/GetDomain',
            platform__pb2.GetDomainRequest.SerializeToString,
            platform__pb2.Domain.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProcessorOSList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/GetProcessorOSList',
            platform__pb2.GetProcessorOSListRequest.SerializeToString,
            platform__pb2.OSProcessorList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTemplateList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/GetTemplateList',
            platform__pb2.GetTemplateRequest.SerializeToString,
            platform__pb2.TemplateList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RetargetFSBL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/RetargetFSBL',
            platform__pb2.ReTargetFSBLRequest.SerializeToString,
            platform__pb2.Domain.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBSPData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/GetBSPData',
            bsp__pb2.BSPDataRequest.SerializeToString,
            bsp__pb2.BSPData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDrivers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/GetDrivers',
            bsp__pb2.BSPDataRequest.SerializeToString,
            bsp__pb2.BSPDriversResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetConfiguredLibraries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/GetConfiguredLibraries',
            bsp__pb2.BSPDataRequest.SerializeToString,
            bsp__pb2.BSPLibrariesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSupportedLibraries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/GetSupportedLibraries',
            bsp__pb2.BSPDataRequest.SerializeToString,
            bsp__pb2.BSPLibrariesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBSPOSInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/GetBSPOSInfo',
            bsp__pb2.BSPDataRequest.SerializeToString,
            bsp__pb2.OS.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBSPProcessorInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/GetBSPProcessorInfo',
            bsp__pb2.BSPDataRequest.SerializeToString,
            bsp__pb2.Processor.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListBSPParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/ListBSPParameters',
            bsp__pb2.BSPParameterRequest.SerializeToString,
            bsp__pb2.BSPParameterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListBSPLibraryParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/ListBSPLibraryParameters',
            bsp__pb2.BSPLibraryRequest.SerializeToString,
            bsp__pb2.BSPParameterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateBSPParameter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/UpdateBSPParameter',
            bsp__pb2.BSPParameterUpdateRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateBSPLibraryParameter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/UpdateBSPLibraryParameter',
            bsp__pb2.BSPLibraryParameterUpdateRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddBSPLibrary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/AddBSPLibrary',
            bsp__pb2.BSPLibraryRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveBSPLibrary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/RemoveBSPLibrary',
            bsp__pb2.BSPLibraryRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBSPParameter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/GetBSPParameter',
            bsp__pb2.BSPParameterDataRequest.SerializeToString,
            bsp__pb2.BSPParameter.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBSPLibraryParameter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/GetBSPLibraryParameter',
            bsp__pb2.BSPLibraryParameterDataRequest.SerializeToString,
            bsp__pb2.BSPParameter.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def validateBSP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/validateBSP',
            platform__pb2.ValidateTemplateRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegenerateBSP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/xilinx.rigel.platform.v3.Platform/RegenerateBSP',
            bsp__pb2.RegenerateBSPRequest.SerializeToString,
            platform__pb2.PlatformResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CleanPlatform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/xilinx.rigel.platform.v3.Platform/CleanPlatform',
            platform__pb2.CleanPlatformRequest.SerializeToString,
            platform__pb2.PlatformResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateHwXSA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/xilinx.rigel.platform.v3.Platform/UpdateHwXSA',
            platform__pb2.UpdatePlatformRequest.SerializeToString,
            platform__pb2.PlatformResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateBif(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/GenerateBif',
            platform__pb2.GenerateBifRequest.SerializeToString,
            platform__pb2.Domain.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateEmbeddedRepoData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/GenerateEmbeddedRepoData',
            platform__pb2.GenerateEmbeddedRepoDataRequest.SerializeToString,
            platform__pb2.GenerateEmbeddedRepoDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEmbeddedRepoData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/GetEmbeddedRepoData',
            platform__pb2.GetEmbeddedRepoDataRequest.SerializeToString,
            platform__pb2.GetEmbeddedRepoDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetEmbeddedRepoData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/SetEmbeddedRepoData',
            platform__pb2.SetEmbeddedRepoDataRequest.SerializeToString,
            platform__pb2.SetEmbeddedRepoDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateBSPPropertyPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/UpdateBSPPropertyPath',
            bsp__pb2.BSPUpdatePathRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetHwXsaSpecification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/GetHwXsaSpecification',
            platform__pb2.HwXsaDataRequest.SerializeToString,
            platform__pb2.HwXsaDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetHWXSAPropertyInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/GetHWXSAPropertyInfo',
            platform__pb2.HWXSAPropertyInfoRequest.SerializeToString,
            platform__pb2.HWXSAPropertyInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExtractHwFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/ExtractHwFiles',
            platform__pb2.ExtractHwFilesRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPartFromXSA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.platform.v3.Platform/GetPartFromXSA',
            platform__pb2.GetPartFromXSARequest.SerializeToString,
            platform__pb2.GetPartFromXSAResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
