# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import utils_pb2 as utils__pb2


class UtilsServiceStub(object):
    """For basic utility services
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetServerEnv = channel.unary_unary(
                '/xilinx.rigel.utils.v1.UtilsService/GetServerEnv',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                )
        self.GetServerEnvEnabled = channel.unary_unary(
                '/xilinx.rigel.utils.v1.UtilsService/GetServerEnvEnabled',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
                )
        self.GetInstallInfo = channel.unary_unary(
                '/xilinx.rigel.utils.v1.UtilsService/GetInstallInfo',
                request_serializer=utils__pb2.GetInstallInfoRequest.SerializeToString,
                response_deserializer=utils__pb2.GetInstallInfoResponse.FromString,
                )
        self.GetInstallFileUri = channel.unary_unary(
                '/xilinx.rigel.utils.v1.UtilsService/GetInstallFileUri',
                request_serializer=utils__pb2.GetFileUriRequest.SerializeToString,
                response_deserializer=utils__pb2.GetFileUriResponse.FromString,
                )
        self.GetDataDirFileUri = channel.unary_unary(
                '/xilinx.rigel.utils.v1.UtilsService/GetDataDirFileUri',
                request_serializer=utils__pb2.GetFileUriRequest.SerializeToString,
                response_deserializer=utils__pb2.GetFileUriResponse.FromString,
                )
        self.TerminateProcess = channel.unary_unary(
                '/xilinx.rigel.utils.v1.UtilsService/TerminateProcess',
                request_serializer=utils__pb2.TerminateProcessRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.ImportFiles = channel.unary_unary(
                '/xilinx.rigel.utils.v1.UtilsService/ImportFiles',
                request_serializer=utils__pb2.ImportFilesRequest.SerializeToString,
                response_deserializer=utils__pb2.ImportRemoveFilesResponse.FromString,
                )
        self.RemoveFiles = channel.unary_unary(
                '/xilinx.rigel.utils.v1.UtilsService/RemoveFiles',
                request_serializer=utils__pb2.RemoveFilesRequest.SerializeToString,
                response_deserializer=utils__pb2.ImportRemoveFilesResponse.FromString,
                )
        self.checkVitisHlsLicense = channel.unary_unary(
                '/xilinx.rigel.utils.v1.UtilsService/checkVitisHlsLicense',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
                )


class UtilsServiceServicer(object):
    """For basic utility services
    """

    def GetServerEnv(self, request, context):
        """Get the value of the specified environment variable
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerEnvEnabled(self, request, context):
        """Get the state of the specified feature toggle (from environment variable with same name)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInstallInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInstallFileUri(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDataDirFileUri(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TerminateProcess(self, request, context):
        """Terminates the uniquely matched process
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportFiles(self, request, context):
        """Import files to the project
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFiles(self, request, context):
        """Remove files from the project
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def checkVitisHlsLicense(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UtilsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetServerEnv': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerEnv,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            ),
            'GetServerEnvEnabled': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerEnvEnabled,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
            ),
            'GetInstallInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInstallInfo,
                    request_deserializer=utils__pb2.GetInstallInfoRequest.FromString,
                    response_serializer=utils__pb2.GetInstallInfoResponse.SerializeToString,
            ),
            'GetInstallFileUri': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInstallFileUri,
                    request_deserializer=utils__pb2.GetFileUriRequest.FromString,
                    response_serializer=utils__pb2.GetFileUriResponse.SerializeToString,
            ),
            'GetDataDirFileUri': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDataDirFileUri,
                    request_deserializer=utils__pb2.GetFileUriRequest.FromString,
                    response_serializer=utils__pb2.GetFileUriResponse.SerializeToString,
            ),
            'TerminateProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.TerminateProcess,
                    request_deserializer=utils__pb2.TerminateProcessRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ImportFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportFiles,
                    request_deserializer=utils__pb2.ImportFilesRequest.FromString,
                    response_serializer=utils__pb2.ImportRemoveFilesResponse.SerializeToString,
            ),
            'RemoveFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFiles,
                    request_deserializer=utils__pb2.RemoveFilesRequest.FromString,
                    response_serializer=utils__pb2.ImportRemoveFilesResponse.SerializeToString,
            ),
            'checkVitisHlsLicense': grpc.unary_unary_rpc_method_handler(
                    servicer.checkVitisHlsLicense,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xilinx.rigel.utils.v1.UtilsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UtilsService(object):
    """For basic utility services
    """

    @staticmethod
    def GetServerEnv(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.utils.v1.UtilsService/GetServerEnv',
            google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServerEnvEnabled(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.utils.v1.UtilsService/GetServerEnvEnabled',
            google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInstallInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.utils.v1.UtilsService/GetInstallInfo',
            utils__pb2.GetInstallInfoRequest.SerializeToString,
            utils__pb2.GetInstallInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInstallFileUri(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.utils.v1.UtilsService/GetInstallFileUri',
            utils__pb2.GetFileUriRequest.SerializeToString,
            utils__pb2.GetFileUriResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDataDirFileUri(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.utils.v1.UtilsService/GetDataDirFileUri',
            utils__pb2.GetFileUriRequest.SerializeToString,
            utils__pb2.GetFileUriResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TerminateProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.utils.v1.UtilsService/TerminateProcess',
            utils__pb2.TerminateProcessRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ImportFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.utils.v1.UtilsService/ImportFiles',
            utils__pb2.ImportFilesRequest.SerializeToString,
            utils__pb2.ImportRemoveFilesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.utils.v1.UtilsService/RemoveFiles',
            utils__pb2.RemoveFilesRequest.SerializeToString,
            utils__pb2.ImportRemoveFilesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def checkVitisHlsLicense(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xilinx.rigel.utils.v1.UtilsService/checkVitisHlsLicense',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
